print('Olá,Mundo ')
print('aula texte')
print('primeira aula')
print('da Julia ')
print('dia 6/12/2024 ' )
print('a aula começou as 10:00 hrs e')
print('vai terminar as 12:00')
print('estamos aprendendo a criar um arquivo')
print('usando varias ferramentas diferentes')
print('incluindo esta e sites que já vimos antes')